# Generated by Django 4.2.3 on 2023-11-11 17:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_subtask_alter_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_contacts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Hanami'), (2, 'test'), (3, 'test2')], max_length=300),
        ),
    ]
